name: AWS Management Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  manage-aws-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your preferred region

      - name: Start Lambda Function
        id: start_lambda
        run: |
          aws lambda put-function-concurrency --function-name function1 --reserved-concurrent-executions 0
          echo "Lambda function concurrency set."

      - name: Start ECS Task
        id: start_ecs
        run: |
          aws ecs update-service --cluster Mycluster --service Service --desired-count 2
          echo "ECS service updated."

      - name: Start EC2 Instances
        id: start_ec2
        run: |
          aws ec2 start-instances --instance-ids i-09a914e0c844e384e i-0e8a814bc49b82b16
          echo "EC2 instances started."

      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          STATUS_TEXT="Deployment Status:\n"
          STATUS_TEXT+="Lambda function concurrency updated.\n"
          STATUS_TEXT+="ECS Service started.\n"
          STATUS_TEXT+="EC2 Instances started."

          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "'"$STATUS_TEXT"'"
          }' $SLACK_WEBHOOK_URL
