name: Triggered from Lambda

on:
  workflow_dispatch:
  # You can add additional triggers here if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "Workflow triggered successfully!"
