name: Triggered Workflow

on:
  repository_dispatch:
    types: [lambda_trigger]  # Custom event type

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Triggered by AWS Lambda!"
