name: AWS Management Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  manage-aws-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your preferred region

      - name: Start Lambda Function
        id: start_lambda
        run: |
          aws lambda put-function-concurrency --function-name function1 --reserved-concurrent-executions 0
          echo "Lambda function concurrency set."
